# Homework Title: Hashing
# Author : Halil Arda Özongun
# ID: 22202709
# Section : 1
# Homework : 3
# Description : Makefile for the homework

build:
	g++ substrings.cpp -o substrings
	g++ minimalset.cpp -o minimalset
	g++ linkedList.h lexicographic.cpp -o lexicographic
	g++ insertionorders.cpp -o insertionorders
