# Homework Title: Heap and AVL Trees
# Author : Halil Arda Özongun
# ID: 22202709
# Section : 1
# Homework : 2
# Description : This is the makefile for the homework. It compiles the files and runs the executables.


build:
	g++ least5.cpp Heap.h -o least5
	g++ prefixsubarray.cpp Heap.h -o prefixsubarray
	g++ subarray.cpp AVL_Tree.h AVL_Tree.cpp -o subarray
	g++ game.cpp AVL_Tree.h AVL_Tree.cpp -o game


