# Homework Title: Heap and AVL Trees
# Author : Halil Arda Özongun
# ID: 22202709
# Section : 1
# Homework : 1
# Description : This is the makefile for the homework. It compiles the files and runs the executables.


build:
	g++ least5.cpp Heap.h -o least5
	#g++ game1.cpp AVL.cpp -o game1

run:
	./least5 inputLeast5.txt outputLeast5.txt
	#./game1 inputGame1.txt outputGame1.txt

clean:
	rm -f *.o least5
	#rm -f *.o game1